# Generated by Django 4.2.5 on 2024-04-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('procedure', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '产品表',
                'db_table': 'tb_product',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '产品详情表',
                'db_table': 'tb_productdetail',
            },
        ),
        migrations.CreateModel(
            name='TestUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('function', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='power.product')),
            ],
            options={
                'verbose_name': '测试用例表',
                'db_table': 'tb_testunit',
            },
        ),
        migrations.CreateModel(
            name='UnitParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
                ('testunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power.testunit')),
            ],
            options={
                'verbose_name': '用例参数表',
                'db_table': 'tb_unitparam',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='productdetail',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='power.productdetail'),
        ),
        migrations.CreateModel(
            name='GlobalParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=32)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='power.product')),
            ],
            options={
                'verbose_name': '全局参数表',
                'db_table': 'tb_globalparam',
            },
        ),
    ]
